params:
  app_name : "mlops-sagemaker"
  execution_role_arn : 'arn:aws:iam::966180254834:role/Sagermaker-role'
  image_ecr_url : "966180254834.dkr.ecr.ap-south-1.amazonaws.com/mlflow-pyfunc:1.23.1"
  region : "ap-south-1"
  s3_bucket_name : "mlops-sagemaker-runs-exp"
  experiment_id : "0"
  run_id : "8f768d3a7f62412c91b6a9627ef19b39"
  model_name : "model"

